Written first version of README.md
MidasLamb/CSSchedule pull request #18
Opened 2017-10-02 12:37 UTC by jonahbellemans

Added first version of a readme file with brief instructions about the usage of the platform.

2017-10-02 13:11 UTC, MidasLamb requested changes
Update the image to the new design. Also fix merge conflict please.

2017-10-02 13:18 UTC, MidasLamb requested changes
Fix merge plz.

2017-10-02 13:18 UTC, MidasLamb commented on README.md
> +This schedule can be imported in most calendar apps, such as Google calendar or iCal. English courses are taken into consideration as counterparts for their Dutch equivalents.
The counterparts have to be selected manually still.

2017-10-02 13:18 UTC, MidasLamb commented on README.md
> +![Screenshot Usage](/images/Screenshot_20171002_142820.png)
Outdated image

2017-10-03 13:08 UTC, jonahbellemans commented
All reviews should be fixed now.

2017-10-03 14:31 UTC, MidasLamb approved these changes

2017-10-03 14:31 UTC, merged