Cookie banner added
MidasLamb/CSSchedule pull request #51
Opened 2018-10-03 09:14 UTC by pcoenen

2018-10-03 09:19 UTC, MidasLamb requested changes

2018-10-03 09:19 UTC, MidasLamb commented on views/home.php
> +			    "message": "This website uses cookies to personalise content and to analyse our traffic."
"Analyse our traffic" should be removed.

2018-10-03 09:24 UTC, pcoenen commented
Changed

2018-10-03 09:30 UTC, MidasLamb commented
![image](https://user-images.githubusercontent.com/14802865/46402223-719ee900-c6ff-11e8-8dac-d8f82825846d.png)
Cookie banner messes with the existing cookies after accepting it (see url on the right of the screenshot). Maybe there is an option for the cookiebanner to put it's save-token elsewhere? Localstorage maybe? 

The bug occurs after selecting courses and accepting the cookie, and then refreshing twice.

2018-10-05 07:09 UTC, pcoenen commented
I put the courses in local storage

2018-10-05 07:11 UTC, MidasLamb approved these changes
I'm just assuming it works now

2018-10-05 07:14 UTC, merged

2018-10-05 07:19 UTC, MidasLamb commented
Unfortunately, this is not backwards compatible.